version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "xebia-achaudhari"
    allowed_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "security"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "semver:patch"
      - match:
          dependency_type: "production"
          update_type: "semver:patch"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
